import React, { useState } from 'react';
import { HelpCircle, ChevronDown, ChevronUp, CheckCircle2, AlertCircle, Lightbulb } from 'lucide-react';
import { useTranslation } from '../context/LanguageContext';

export type ExplainerMetricType = 'wbgt' | 'riskScore' | 'heatIndex' | 'clo' | 'metabolic';

interface MetricExplainerProps {
  metricType: ExplainerMetricType;
  customLabel?: string;
  className?: string;
}

export const MetricExplainer: React.FC<MetricExplainerProps> = ({
  metricType,
  customLabel,
  className = '',
}) => {
  const { t } = useTranslation();
  const [isExpanded, setIsExpanded] = useState<boolean>(false);

  const getContent = () => {
    switch (metricType) {
      case 'wbgt':
        return {
          meaning: t(
            'explainer.wbgtMeaning',
            undefined,
            'Estimated Wet-Bulb Globe Temperature (WBGT) is an analytical biometeorological calculation derived from ambient air temperature, relative humidity, solar radiation, and wind. It is an analytical meteorological estimate, not a physical black-globe sensor measurement.'
          ),
          why: t(
            'explainer.wbgtWhy',
            undefined,
            'High humidity prevents sweat from evaporating, so your body struggles to release internal heat even at lower air temperatures.'
          ),
          action: t(
            'explainer.wbgtAction',
            undefined,
            'When estimated WBGT exceeds 30°C, take 15-minute shaded rest breaks every hour and drink water or electrolytes frequently.'
          ),
        };
      case 'riskScore':
        return {
          meaning: t(
            'explainer.riskScoreMeaning',
            undefined,
            'ThermoShield Composite Thermal Strain Index: A 0 to 100 planning and guidance score combining biometeorological calculations, local vulnerability weighting, and predictive models.'
          ),
          why: t(
            'explainer.riskScoreWhy',
            undefined,
            'Scores above 50 indicate elevated physiological strain. Scores above 75 warn of critical heat risk where heat exhaustion can occur rapidly.'
          ),
          action: t(
            'explainer.riskScoreAction',
            undefined,
            'Avoid heavy outdoor physical exertion, stay in shaded or ventilated spaces, and check on family members.'
          ),
        };
      case 'heatIndex':
        return {
          meaning: t(
            'explainer.heatIndexMeaning',
            undefined,
            'The "Feels Like" temperature in the shade, calculated from actual air temperature and relative humidity.'
          ),
          why: t(
            'explainer.heatIndexWhy',
            undefined,
            'Humid air feels significantly hotter than dry air because skin moisture cannot evaporate quickly.'
          ),
          action: t(
            'explainer.heatIndexAction',
            undefined,
            'Use electric fans with ventilation, spray cool water on your skin, and minimize direct sun exposure.'
          ),
        };
      case 'clo':
        return {
          meaning: t(
            'explainer.cloMeaning',
            undefined,
            'Clothing Insulation (clo) measures how much your clothes trap heat (0.3 clo for light cotton up to 1.0 clo for thick work uniforms).'
          ),
          why: t(
            'explainer.cloWhy',
            undefined,
            'Heavy or synthetic fabrics trap hot air near your skin and prevent sweat from evaporating.'
          ),
          action: t(
            'explainer.cloAction',
            undefined,
            'Wear loose, light-colored, single-layer breathable cotton or linen garments.'
          ),
        };
      case 'metabolic':
        return {
          meaning: t(
            'explainer.metabolicMeaning',
            undefined,
            'Metabolic Work Rate (Watts) measures the internal body heat generated by physical activity (100W resting to 400W+ manual labor).'
          ),
          why: t(
            'explainer.metabolicWhy',
            undefined,
            'Hard physical work rapidly generates internal heat that your heart and cardiovascular system must pump to the skin.'
          ),
          action: t(
            'explainer.metabolicAction',
            undefined,
            'Slow down your pace, take scheduled cool-down rests, and never ignore early signs of dizziness or cramps.'
          ),
        };
    }
  };

  const content = getContent();

  return (
    <div className={`text-xs ${className}`}>
      <button
        type="button"
        onClick={() => setIsExpanded(!isExpanded)}
        className="inline-flex items-center gap-1.5 py-1 px-2 rounded-lg ts-card-subtle border ts-border text-slate-700 dark:text-slate-300 hover:ts-text-primary transition-colors cursor-pointer font-medium text-[11px]"
        aria-expanded={isExpanded}
      >
        <HelpCircle className="w-3.5 h-3.5 text-orange-600 dark:text-orange-400 flex-shrink-0" />
        <span>{customLabel || t('explainer.whatDoesThisMean', undefined, 'What does this mean?')}</span>
        {isExpanded ? (
          <ChevronUp className="w-3 h-3 text-slate-500 dark:text-slate-400 ml-0.5" />
        ) : (
          <ChevronDown className="w-3 h-3 text-slate-500 dark:text-slate-400 ml-0.5" />
        )}
      </button>

      {isExpanded && (
        <div className="mt-2 p-3 rounded-xl ts-card-subtle border border-orange-500/30 space-y-2 text-[11px] leading-relaxed animate-in fade-in-50 duration-200">
          <div className="flex items-start gap-2">
            <Lightbulb className="w-3.5 h-3.5 text-amber-600 dark:text-amber-400 mt-0.5 flex-shrink-0" />
            <div>
              <span className="font-bold ts-text-primary block">
                {t('explainer.meaning', undefined, 'What it is:')}
              </span>
              <p className="ts-text-muted mt-0.5">{content.meaning}</p>
            </div>
          </div>

          <div className="flex items-start gap-2">
            <AlertCircle className="w-3.5 h-3.5 text-orange-600 dark:text-orange-400 mt-0.5 flex-shrink-0" />
            <div>
              <span className="font-bold ts-text-primary block">
                {t('explainer.whyItMatters', undefined, 'Why it matters:')}
              </span>
              <p className="ts-text-muted mt-0.5">{content.why}</p>
            </div>
          </div>

          <div className="flex items-start gap-2">
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400 mt-0.5 flex-shrink-0" />
            <div>
              <span className="font-bold text-emerald-700 dark:text-emerald-400 block">
                {t('explainer.suggestedAction', undefined, 'Suggested action:')}
              </span>
              <p className="text-emerald-700 dark:text-emerald-300/90 mt-0.5 font-medium">{content.action}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
export default MetricExplainer;
